# Generated by Django 6.0 on 2025-12-12 16:49

import financeiro.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='competencia',
            field=financeiro.models.CompetenciaField(verbose_name='Competência (AAAAMM)'),
        ),
    ]
